version: '3.8'
services:

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./
    container_name: auto
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
      - QUARKUS_MONGODB_DATABASE=auto-laudo

volumes:
  mongodb_data:
